name: Rust Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build for ARM64
        run: cargo build --release --target=aarch64-apple-darwin

      - name: Build for x86
        run: cargo build --release --target=x86_64-apple-darwin

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: |
            target/aarch64-apple-darwin/release/ # ARM64 binary
            target/x86_64-apple-darwin/release/ # x86 binary
